In [2]:
## 로지스틱 회귀분석
# 데이터 'breast-cancer-wisconsin.csv'
# 저장 classfication_test.csv

In [4]:
# 1.데이터 불러오기
import pandas as pd
data1 = pd.read_csv('breast-cancer-wisconsin.csv', encoding = 'utf-8')
data1.tail()

,code,Clump_Thickness,Cell_Size,Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class
678,776715,3,1,1,1,3,2,1,1,1,0
679,841769,2,1,1,1,2,1,1,1,1,0
680,888820,5,10,10,3,7,3,8,10,2,1
681,897471,4,8,6,4,3,4,10,6,1,1
682,897471,4,8,8,5,4,5,10,4,1,1

In [6]:
data1.describe()

,code,Clump_Thickness,Cell_Size,Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class
count,6.830000e+02,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000
mean,1.076720e+06,4.442167,3.150805,3.215227,2.830161,3.234261,3.544656,3.445095,2.869693,1.603221,0.349927
std,6.206440e+05,2.820761,3.065145,2.988581,2.864562,2.223085,3.643857,2.449697,3.052666,1.732674,0.477296
min,6.337500e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,8.776170e+05,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,0.000000
50%,1.171795e+06,4.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,1.000000,1.000000,0.000000
75%,1.238705e+06,6.000000,5.000000,5.000000,4.000000,4.000000,6.000000,5.000000,4.000000,1.000000,1.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000

In [7]:
# 2.데이터 전처리
# x,y 나누기
x1 = data1[['Clump_Thickness', 'Cell_Size', 'Cell_Shape', 'Marginal_Adhesion', 'Single_Epithelial_Cell_Size'
          , 'Bare_Nuclei', 'Bland_Chromatin', 'Normal_Nucleoli', 'Mitoses']]
y1 = data1[['Class']]

In [14]:
# test, train 데이터 나누기
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, random_state = 1)

In [15]:
y1_train.mean()

Class    0.349609
dtype: float64

In [16]:
y1_test.mean()

Class    0.350877
dtype: float64

In [26]:
# 데이터 정규화 - minmax
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler()
minmax_scaler.fit(x1_train)
# train data 
x1_train_minmax_scaler = minmax_scaler.transform(x1_train)
x1_train_minmax_scaler

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.33333333, 0.        , 0.11111111, ..., 0.11111111, 0.        ,
        0.        ],
       [0.66666667, 0.33333333, 0.66666667, ..., 0.66666667, 0.55555556,
        0.        ],
       ...,
       [1.        , 0.55555556, 0.33333333, ..., 0.22222222, 0.11111111,
        0.22222222],
       [0.11111111, 0.        , 0.        , ..., 0.22222222, 0.        ,
        0.        ],
       [0.44444444, 0.33333333, 0.33333333, ..., 0.44444444, 0.55555556,
        0.        ]])

In [27]:
# test data 
x1_test_minmax_scaler = minmax_scaler.transform(x1_test)
x1_test_minmax_scaler

array([[0.44444444, 0.        , 0.        , ..., 0.11111111, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.22222222, 0.        ,
        0.        ],
       [0.33333333, 0.        , 0.        , ..., 0.22222222, 0.        ,
        0.        ],
       ...,
       [0.33333333, 0.        , 0.        , ..., 0.22222222, 0.        ,
        0.        ],
       [0.33333333, 0.        , 0.        , ..., 0.11111111, 0.        ,
        0.        ],
       [0.22222222, 0.        , 0.        , ..., 0.11111111, 0.        ,
        0.        ]])