In [1]:
# 1) 데이터 전체에서 80% 추출 후 결측치들을 median으로 채우고 표준편차의 변화값:

In [37]:
import pandas as pd
data1 = pd.read_csv('house_price.csv', encoding = 'utf-8')
data1.tail()

       housing_age  income  bedrooms  households     rooms  house_value
17684           34  2.3013  0.214583    2.748299  4.897959        26600
17685           33  2.6750  0.246622    3.428571  4.698413        22500
17686           39  2.3667  0.340771    1.876812  3.572464        17500
17687           19  2.1000  0.386107    2.987805  3.774390        14999
17688           16  1.6607  0.286275    2.236842  6.710526        14999

In [38]:
data2 = data1[:100]
data2['income2'] = data2['income']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [39]:
import numpy as np
data2['income2'][data2['income2'] < 3.6] = np.NAN

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:7626: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2961: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [40]:
std1 = data2['income2'].std()
std1

1.4776616329431542

In [41]:
med1 = data2['income2'].median()
med1

6.3521

In [42]:
data2['income3'] = data2['income2']
data2['income3'][data2['income3'].isna()] = med1
data2

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:7626: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2961: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

,housing_age,income,bedrooms,households,rooms,house_value,income2,income3
0,23,6.7770,0.141112,2.442244,8.103960,500000,6.7770,6.7770
1,49,6.0199,0.160984,2.726688,5.752412,500000,6.0199,6.0199
2,35,5.1155,0.249061,1.902676,3.888078,500000,5.1155,5.1155
3,32,4.7109,0.231383,1.913669,4.508393,500000,4.7109,4.7109
4,21,4.5625,0.255583,3.092664,4.667954,500000,4.5625,4.5625
5,38,4.3403,0.268350,1.768000,5.068000,500000,4.3403,4.3403
6,25,3.9696,0.116477,2.911765,10.352941,500000,3.9696,3.9696
7,34,3.7306,0.272993,1.507270,3.864297,500000,3.7306,3.7306
8,29,3.6250,0.258112,1.626728,4.213518,500000,3.6250,3.6250
9,29,3.6121,0.277360,1.719258,4.006961,500000,3.6121,3.6121
10,31,3.5744,0.251751,2.095351,4.163121,500000,NaN,6.3521
11,25,3.5556,0.258405,1.860063,4.022013,500000,NaN,6.3521
12,44,2.6103,0.295530,2.030303,4.067340,500000,NaN,6.3521
13,26,2.3536,0.353787,3.973438,2.826563,500000,NaN,6.3521
14,20,2.2444,0.375408,2.358090,2.977011,500000,NaN,6.3521
15,26,1.9891,0.277710,1.902793,4.606704,500000,NaN,6.3521
16,19,1.2656,0.304878,1.433526,3.791908,500000,NaN,6.3521
17,28,6.7861,0.146739,2.251825,7.386861,499100,6.7861,6.7861
18,18,8.1489,0.151703,2.226158,6.600817,499000,8.1489,8.1489
19,29,8.2480,0.138303,3.003636,7.072727,498800,8.2480,8.2480
20,40,7.2692,0.156981,2.190821,6.816425,498700,7.2692,7.2692
21,33,5.7380,0.183805,1.984615,5.984615,497600,5.7380,5.7380
22,40,3.5637,0.246415,1.712230,4.414388,497400,NaN,6.3521
23,21,7.9135,0.140180,2.445714,7.928571,496400,7.9135,7.9135
24,33,6.5970,0.135957,2.631799,7.016736,496400,6.5970,6.5970
25,17,5.9285,0.160832,2.342043,6.513064,496000,5.9285,5.9285
26,44,6.7058,0.156519,2.589099,6.335430,495900,6.7058,6.7058
27,21,4.3125,0.194025,2.396000,11.380000,495800,4.3125,4.3125
28,36,8.0499,0.171736,1.961062,6.080531,495600,8.0499,8.0499
29,38,3.6181,0.259600,1.665150,4.051865,495600,3.6181,3.6181
...,...,...,...,...,...,...,...,...
70,30,6.3624,0.130137,2.423077,5.615385,483300,6.3624,6.3624
71,28,3.3266,0.290076,1.594073,3.521020,483300,NaN,6.3521
72,34,4.4980,0.228111,1.775766,4.756267,482900,4.4980,4.4980
73,35,6.3612,0.149949,2.510843,7.038554,482700,6.3612,6.3612
74,33,6.8553,0.156219,2.701872,6.760695,482200,6.8553,6.8553
75,36,6.6321,0.184233,2.538084,5.734644,481500,6.6321,6.6321
76,29,7.6526,0.144608,2.561605,7.014327,481300,7.6526,7.6526
77,17,6.3892,0.155606,2.477713,6.438953,480800,6.3892,6.3892
78,19,6.3230,0.146075,3.444186,6.813953,480800,6.3230,6.3230
79,36,5.3441,0.169478,2.298643,5.633484,480600,5.3441,5.3441
80,44,6.1014,0.170055,2.507853,5.280105,480100,6.1014,6.1014
81,49,5.1072,0.180937,2.226721,5.989204,479700,5.1072,5.1072
82,40,6.4350,0.221560,1.867532,4.361039,479500,6.4350,6.4350
83,38,3.7500,0.165680,3.063415,5.770732,478600,3.7500,3.7500
84,10,8.7991,0.156903,2.392947,9.287154,478500,8.7991,8.7991
85,20,4.5656,0.206140,1.771580,5.147410,478400,4.5656,4.5656
86,44,7.9213,0.151792,2.492925,6.448113,477800,7.9213,7.9213
87,25,8.0580,0.145590,2.947853,6.815951,477300,8.0580,8.0580
88,24,5.9055,0.154950,2.356764,6.470822,477300,5.9055,5.9055
89,24,3.9673,0.247651,1.806271,4.291153,477300,3.9673,3.9673
90,36,7.2772,0.134777,2.813239,7.858156,477200,7.2772,7.2772
91,38,7.9059,0.162483,2.506849,6.547945,477100,7.9059,7.9059
92,20,3.5500,0.183787,2.708235,6.138824,476700,NaN,6.3521
93,36,7.8407,0.142889,2.827303,7.274671,476400,7.8407,7.8407
94,47,5.0203,0.188462,2.470968,5.591398,476300,5.0203,5.0203
95,29,7.0309,0.217759,4.126437,5.436782,475000,7.0309,7.0309
96,6,3.7292,0.236364,2.875000,4.583333,475000,3.7292,3.7292
97,28,2.9125,0.295481,2.279823,3.748159,475000,NaN,6.3521
98,20,2.4444,0.136842,2.066667,6.333333,475000,NaN,6.3521
99,21,1.8214,0.376263,2.597753,2.966292,475000,NaN,6.3521

In [43]:
std2 = data2['income3'].std()
std2

1.3464860246571333

In [44]:
diff = std2 - std1
print(diff)

-0.13117560828602093