<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#로지스틱-회귀분석-과제" data-toc-modified-id="로지스틱-회귀분석-과제-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>로지스틱 회귀분석 과제</a></span></li></ul></div>

# 로지스틱 회귀분석 과제 

- 1) 타이타닉 데이터를 불러오고 survived를 종속변수(y)로, 나머지 변수들은 독립변수(X)로 설정하세요

In [69]:
import pandas as pd 
df_t = pd.read_csv("C:/adp/data/titanic.csv")
df_t.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

- 2) X의 결측치가 존재하는 행을 삭제하고, 범주형 변수를 더미변수화 시키세요

In [70]:
df_t = df_t.drop(columns=['who', 'deck', 'alive', 'alone', 'class', 'embark_town'])
df_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    object
 3   age         714 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   embarked    889 non-null    object
 8   adult_male  891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [71]:
# X의 결측치가 존재하는 행을 삭제
df_t2 = df_t.dropna()
df_t2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    712 non-null    int64
 1   pclass      712 non-null    int64
 2   sex         712 non-null    object
 3   age         712 non-null    float64
 4   sibsp       712 non-null    int64
 5   parch       712 non-null    int64
 6   fare        712 non-null    float64
 7   embarked    712 non-null    object
 8   adult_male  712 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 50.8+ KB

In [72]:
# survived를 종속변수(y)로, 나머지 변수들은 독립변수(X)로 설정
Y = df_t2.survived
X = df_t2.drop(['survived'],axis=1)

In [73]:
# 범주형 변수를 더미변수화
X = pd.get_dummies(X, columns = ['sex','embarked','adult_male'])
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   pclass            712 non-null    int64
 1   age               712 non-null    float64
 2   sibsp             712 non-null    int64
 3   parch             712 non-null    int64
 4   fare              712 non-null    float64
 5   sex_female        712 non-null    uint8
 6   sex_male          712 non-null    uint8
 7   embarked_C        712 non-null    uint8
 8   embarked_Q        712 non-null    uint8
 9   embarked_S        712 non-null    uint8
 10  adult_male_False  712 non-null    uint8
 11  adult_male_True   712 non-null    uint8
dtypes: float64(2), int64(3), uint8(7)
memory usage: 38.2 KB

In [109]:
X.shape

(712, 12)

- 3) 독립변수(X)를 StandardScaler를 통해 변환하세요

In [74]:
# 독립변수 설명변수 분리
from sklearn.preprocessing import StandardScaler # 정규화
# 표준 스케일러(평균 0, 분산 1)
scaler = StandardScaler()
# 독립변수 데이터 스케일링
scaler_fit = scaler.fit_transform(X)
X_scaled = pd.DataFrame(scaler_fit, columns=X.columns)
X_scaled.tail()

,pclass,age,sibsp,parch,fare,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,adult_male_False,adult_male_True
707,0.908600,0.646142,-0.552714,5.350885,-0.102875,1.322511,-1.322511,-0.472618,4.942527,-1.872519,1.175275,-1.175275
708,-0.287191,-0.182430,-0.552714,-0.506787,-0.407687,-0.756138,0.756138,-0.472618,-0.202326,0.534040,-0.850865,0.850865
709,-1.482983,-0.734812,-0.552714,-0.506787,-0.086335,1.322511,-1.322511,-0.472618,-0.202326,0.534040,1.175275,-1.175275
710,-1.482983,-0.251478,-0.552714,-0.506787,-0.086335,-0.756138,0.756138,2.115874,-0.202326,-1.872519,-0.850865,0.850865
711,0.908600,0.162808,-0.552714,-0.506787,-0.506928,-0.756138,0.756138,-0.472618,4.942527,-1.872519,-0.850865,0.850865

In [75]:
# na Check
import numpy as np
np.isnan(X_scaled).sum()

pclass              0
age                 0
sibsp               0
parch               0
fare                0
sex_female          0
sex_male            0
embarked_C          0
embarked_Q          0
embarked_S          0
adult_male_False    0
adult_male_True     0
dtype: int64

In [92]:
X_scaled = X_scaled.reset_index(drop = True)
X_scaled = X_scaled.astype(float)
X_scaled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 712 entries, 0 to 711
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   pclass            712 non-null    float64
 1   age               712 non-null    float64
 2   sibsp             712 non-null    float64
 3   parch             712 non-null    float64
 4   fare              712 non-null    float64
 5   sex_female        712 non-null    float64
 6   sex_male          712 non-null    float64
 7   embarked_C        712 non-null    float64
 8   embarked_Q        712 non-null    float64
 9   embarked_S        712 non-null    float64
 10  adult_male_False  712 non-null    float64
 11  adult_male_True   712 non-null    float64
dtypes: float64(12)
memory usage: 66.9 KB

In [102]:
Y = Y.astype(float)
Y.tail()

TypeError: 'tuple' object is not callable

In [104]:
X_scaled[X_scaled.index.isin(y.index)]

,pclass,age,sibsp,parch,fare,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,adult_male_False,adult_male_True
0,0.908600,-0.527669,0.522511,-0.506787,-0.516380,-0.756138,0.756138,-0.472618,-0.202326,0.534040,-0.850865,0.850865
1,-1.482983,0.577094,0.522511,-0.506787,0.694046,1.322511,-1.322511,2.115874,-0.202326,-1.872519,1.175275,-1.175275
2,0.908600,-0.251478,-0.552714,-0.506787,-0.503620,1.322511,-1.322511,-0.472618,-0.202326,0.534040,1.175275,-1.175275
3,-1.482983,0.369951,0.522511,-0.506787,0.350326,1.322511,-1.322511,-0.472618,-0.202326,0.534040,1.175275,-1.175275
4,0.908600,0.369951,-0.552714,-0.506787,-0.501257,-0.756138,0.756138,-0.472618,-0.202326,0.534040,-0.850865,0.850865
...,...,...,...,...,...,...,...,...,...,...,...,...
707,0.908600,0.646142,-0.552714,5.350885,-0.102875,1.322511,-1.322511,-0.472618,4.942527,-1.872519,1.175275,-1.175275
708,-0.287191,-0.182430,-0.552714,-0.506787,-0.407687,-0.756138,0.756138,-0.472618,-0.202326,0.534040,-0.850865,0.850865
709,-1.482983,-0.734812,-0.552714,-0.506787,-0.086335,1.322511,-1.322511,-0.472618,-0.202326,0.534040,1.175275,-1.175275
710,-1.482983,-0.251478,-0.552714,-0.506787,-0.086335,-0.756138,0.756138,2.115874,-0.202326,-1.872519,-0.850865,0.850865
711,0.908600,0.162808,-0.552714,-0.506787,-0.506928,-0.756138,0.756138,-0.472618,4.942527,-1.872519,-0.850865,0.850865

- 4) X와 y를 홀드아웃 기법을 사용하여 7:3으로 분할하세요

In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, Y, stratify=Y, test_size=0.3, random_state=42)

In [106]:
# y_train=y_train.values.reshape(-1,1)
# y_train

- 5) X_train과 y_train을 가지고 로지스틱 회귀분석모델을 만드세요

In [108]:
import statsmodels.api as sm
model = sm.Logit(y_train, X_train)
result = model.fit()
result.summary()

ValueError: The indices for endog and exog are not aligned

- 6) 변수선택법을 통해 최적의 회귀 방정식을 구하고, 유의한 변수만을 추출하세요. (변수선택법은 복사 붙여넣기)

In [3]:
import time
import itertools
def processSubset(X,y, feature_set):
            model = sm.Logit(y,X[list(feature_set)]) # Modeling
            regr = model.fit() # 모델 학습
            AIC = regr.aic # 모델의 AIC
            return {"model":regr, "AIC":AIC}
        
'''
전진선택법
'''
def forward(X, y, predictors):
    
    # 데이터 변수들이 미리정의된 predictors에 있는지 없는지 확인 및 분류
    remaining_predictors = [p for p in X.columns if p not in predictors]
    results = []
    for p in remaining_predictors:
        results.append(processSubset(X=X, y= y, feature_set=predictors+[p]))
        
    # 데이터프레임으로 변환
    models = pd.DataFrame(results)

    # AIC가 가장 낮은 것을 선택
    best_model = models.loc[models['AIC'].argmin()] # index

    print("Processed ", models.shape[0], "models on", len(predictors)+1, "predictors in")
    print('Selected predictors:',best_model['model'].model.exog_names,' AIC:',best_model[0] )
    return best_model

'''
후진소거법
'''
def backward(X,y,predictors):
    tic = time.time()
    results = []
    
    # 데이터 변수들이 미리정의된 predictors 조합 확인
    for combo in itertools.combinations(predictors, len(predictors) - 1):
        results.append(processSubset(X=X, y= y,feature_set=list(combo)))
    models = pd.DataFrame(results)
    
    # 가장 낮은 AIC를 가진 모델을 선택
    best_model = models.loc[models['AIC'].argmin()]
    toc = time.time()
    print("Processed ", models.shape[0], "models on", len(predictors) - 1, "predictors in",
          (toc - tic))
    print('Selected predictors:',best_model['model'].model.exog_names,' AIC:',best_model[0] )
    return best_model



'''
단계적 선택법
'''

def Stepwise_model(X,y):
    Stepmodels = pd.DataFrame(columns=["AIC", "model"])
    tic = time.time()
    predictors = [X.columns[0]]
    Smodel_before = processSubset(X,y,predictors)['AIC']
    # 변수 1~10개 : 0~9 -> 1~10
    for i in range(1, len(X.columns) + 1):
        Forward_result = forward(X=X, y=y, predictors=predictors) # constant added
        print('forward')
        Stepmodels.loc[i] = Forward_result
        predictors = Stepmodels.loc[i]["model"].model.exog_names
        predictors = [ k for k in predictors]
        Backward_result = backward(X=X, y=y, predictors=predictors)
        if Backward_result['AIC']< Forward_result['AIC']:
            Stepmodels.loc[i] = Backward_result
            predictors = Stepmodels.loc[i]["model"].model.exog_names
            Smodel_before = Stepmodels.loc[i]["AIC"]
            predictors = [ k for k in predictors]
            print('backward')
        if Stepmodels.loc[i]['AIC']> Smodel_before:
            break
        else:
            Smodel_before = Stepmodels.loc[i]["AIC"]
    toc = time.time()
    print("Total elapsed time:", (toc - tic), "seconds.")
    return (Stepmodels['model'][len(Stepmodels['model'])])

- 6) X_test값을 가지고 y_predict값을 구한 후 혼동행렬을 만드세요

- 7) X_test값을 가지고 y_predict_proba 값을 구한 후 roc_auc_score를 구하고 해석하세요

- 7) 회귀계수를 구하고, 유의한 회귀계수의 값을 설명하세요